name: "MAX! to MQTT Bridge"
version: "1.1.0"
slug: "max2mqtt"
description: "Bridge for MAX! Wall Thermostats via CUL-Stick to MQTT in Home Assistant"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
uart: true
options:
  serial_port: "/dev/serial/by-id/usb-SHK_NANO_CUL_868-if00-port0"
  baud_rate: 38400
  log_level: "info"
  mqtt_broker: "tcp://homeassistant.local:1883"
  mqtt_user: ""
  mqtt_pass: ""
  gateway_id: "123456"
  duty_cycle_min_credits: 200
  command_timeout: "1m"
  max_cul_queue: 5
schema:
  serial_port: str
  baud_rate: int
  log_level: list(debug|info|warning|error)
  mqtt_broker: str
  mqtt_user: str
  mqtt_pass: password
  gateway_id: str
  duty_cycle_min_credits: int
  command_timeout: str
  max_cul_queue: int
devices:
  - "/dev/ttyACM0"
  - "/dev/ttyACM1"
  - "/dev/ttyUSB0"
  - "/dev/ttyUSB1"
  - "/dev/serial/by-id"
